version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install --save-dev @babel/cli @babel/core @babel/preset-env
  pre_build:
    commands:
      - echo Preparing build environment...
      - ls
  build:
    commands:
      - echo Building the application...
      - npm run build || echo "Build failed, skipping start phase"
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .
