version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing npm@10 to avoid npm11 peer-deps issues"
      - npm i -g npm@10
      - npm --version
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps --no-audit --no-fund
  pre_build:
    commands:
      - echo "Running unit tests..."
      - npm test || echo "No tests or tests failed, continuing for demo."
  build:
    commands:
      - echo "Building (transpile with Babel)..."
      - npm run build
  post_build:
    commands:
      - echo "Build finished."

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .
