version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Use npm@10 to avoid npm@11 peer-deps behavior"
      - npm i -g npm@10
      - npm --version
      - rm -f package-lock.json
      - rm -rf node_modules
      - npm install --include=dev --legacy-peer-deps --no-audit --no-fund
      - npm i -D @babel/cli@7.26.4 @babel/core@7.26.0 @babel/preset-env@7.26.0 --no-audit --no-fund
      - export PATH="$PWD/node_modules/.bin:$PATH"
      - npx babel --version || true
      - node -v
  pre_build:
    commands:
      - echo "Run tests (soft-fail)"
      - npm test || echo "No tests or tests failed, continuing."
  build:
    commands:
      - echo "Transpile with Babel"
      - npm run build
  post_build:
    commands:
      - echo "Build finished. Preparing artifacts."

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no
